# Generated by Django 2.2 on 2019-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salário')),
                ('horaextra', models.PositiveIntegerField(verbose_name='Hora extra')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
